/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const CommitteeRole = IDL.Variant({
  'member' : IDL.Null,
  'secretary' : IDL.Null,
  'president' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PaymentMode = IDL.Variant({
  'upi' : IDL.Null,
  'cash' : IDL.Null,
  'gPay' : IDL.Null,
  'cheque' : IDL.Null,
  'phonePe' : IDL.Null,
});
export const CommitteeMemberPublic = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'role' : CommitteeRole,
});
export const CommitteeMember = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'role' : CommitteeRole,
  'mobileNumber' : IDL.Text,
});
export const TempleContact = IDL.Record({
  'id' : IDL.Nat,
  'contactType' : IDL.Text,
  'contactNumber' : IDL.Text,
});
export const DonationReport = IDL.Record({
  'totalCollections' : IDL.Nat,
  'totalAmount' : IDL.Nat,
});
export const DonorDetail = IDL.Record({
  'date' : Time,
  'donorName' : IDL.Text,
  'paymentMode' : PaymentMode,
  'amount' : IDL.Nat,
  'transactionId' : IDL.Text,
});
export const GalleryItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'externalBlob' : ExternalBlob,
  'description' : IDL.Text,
  'mediaType' : IDL.Text,
});
export const Jatre = IDL.Record({
  'id' : IDL.Nat,
  'date' : Time,
  'name' : IDL.Text,
  'activities' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
});
export const PaymentStatus = IDL.Variant({
  'pendingVerification' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const PaymentConfirmation = IDL.Record({
  'id' : IDL.Nat,
  'status' : PaymentStatus,
  'verificationDate' : IDL.Opt(Time),
  'date' : Time,
  'donorName' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'amountPaid' : IDL.Nat,
  'paymentMode' : PaymentMode,
  'transactionId' : IDL.Text,
});
export const Receipt = IDL.Record({
  'isCancelled' : IDL.Bool,
  'date' : Time,
  'donorName' : IDL.Text,
  'templeName' : IDL.Text,
  'paymentMode' : PaymentMode,
  'amount' : IDL.Nat,
  'receiver' : IDL.Text,
  'location' : IDL.Text,
  'receiptNumber' : IDL.Nat,
  'transactionId' : IDL.Text,
});
export const TempleAccount = IDL.Record({
  'balance' : IDL.Nat,
  'lastUpdated' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCommitteeMember' : IDL.Func(
      [IDL.Text, CommitteeRole, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addContact' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'addGalleryItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
      [IDL.Nat],
      [],
    ),
  'addJatre' : IDL.Func(
      [IDL.Text, Time, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'adminAdjustBalance' : IDL.Func([IDL.Nat], [], []),
  'approvePayment' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelReceipt' : IDL.Func([IDL.Nat], [], []),
  'editCommitteeMember' : IDL.Func(
      [IDL.Nat, IDL.Text, CommitteeRole, IDL.Text],
      [],
      [],
    ),
  'editContact' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'editGalleryItem' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
  'editJatre' : IDL.Func(
      [IDL.Nat, IDL.Text, Time, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'editPaymentConfirmation' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, PaymentMode, IDL.Text, Time],
      [],
      [],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommitteeMembers' : IDL.Func(
      [],
      [IDL.Vec(CommitteeMemberPublic)],
      ['query'],
    ),
  'getCommitteeMembersAdmin' : IDL.Func(
      [],
      [IDL.Vec(CommitteeMember)],
      ['query'],
    ),
  'getContacts' : IDL.Func([], [IDL.Vec(TempleContact)], ['query']),
  'getDonationReport' : IDL.Func([], [DonationReport], ['query']),
  'getDonorList' : IDL.Func([], [IDL.Vec(DonorDetail)], ['query']),
  'getGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
  'getJatres' : IDL.Func([], [IDL.Vec(Jatre)], ['query']),
  'getPendingPayments' : IDL.Func(
      [],
      [IDL.Vec(PaymentConfirmation)],
      ['query'],
    ),
  'getReceipt' : IDL.Func([IDL.Nat], [Receipt], ['query']),
  'getTempleAccountBalance' : IDL.Func([], [TempleAccount], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'regenerateReceipt' : IDL.Func([IDL.Nat], [Receipt], []),
  'rejectPayment' : IDL.Func([IDL.Nat], [], []),
  'removeCommitteeMember' : IDL.Func([IDL.Nat], [], []),
  'removeContact' : IDL.Func([IDL.Nat], [], []),
  'removeGalleryItem' : IDL.Func([IDL.Nat], [], []),
  'removeJatre' : IDL.Func([IDL.Nat], [], []),
  'submitPaymentConfirmation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, PaymentMode, IDL.Text, Time],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const CommitteeRole = IDL.Variant({
    'member' : IDL.Null,
    'secretary' : IDL.Null,
    'president' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PaymentMode = IDL.Variant({
    'upi' : IDL.Null,
    'cash' : IDL.Null,
    'gPay' : IDL.Null,
    'cheque' : IDL.Null,
    'phonePe' : IDL.Null,
  });
  const CommitteeMemberPublic = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'role' : CommitteeRole,
  });
  const CommitteeMember = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'role' : CommitteeRole,
    'mobileNumber' : IDL.Text,
  });
  const TempleContact = IDL.Record({
    'id' : IDL.Nat,
    'contactType' : IDL.Text,
    'contactNumber' : IDL.Text,
  });
  const DonationReport = IDL.Record({
    'totalCollections' : IDL.Nat,
    'totalAmount' : IDL.Nat,
  });
  const DonorDetail = IDL.Record({
    'date' : Time,
    'donorName' : IDL.Text,
    'paymentMode' : PaymentMode,
    'amount' : IDL.Nat,
    'transactionId' : IDL.Text,
  });
  const GalleryItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'externalBlob' : ExternalBlob,
    'description' : IDL.Text,
    'mediaType' : IDL.Text,
  });
  const Jatre = IDL.Record({
    'id' : IDL.Nat,
    'date' : Time,
    'name' : IDL.Text,
    'activities' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
  });
  const PaymentStatus = IDL.Variant({
    'pendingVerification' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const PaymentConfirmation = IDL.Record({
    'id' : IDL.Nat,
    'status' : PaymentStatus,
    'verificationDate' : IDL.Opt(Time),
    'date' : Time,
    'donorName' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'amountPaid' : IDL.Nat,
    'paymentMode' : PaymentMode,
    'transactionId' : IDL.Text,
  });
  const Receipt = IDL.Record({
    'isCancelled' : IDL.Bool,
    'date' : Time,
    'donorName' : IDL.Text,
    'templeName' : IDL.Text,
    'paymentMode' : PaymentMode,
    'amount' : IDL.Nat,
    'receiver' : IDL.Text,
    'location' : IDL.Text,
    'receiptNumber' : IDL.Nat,
    'transactionId' : IDL.Text,
  });
  const TempleAccount = IDL.Record({
    'balance' : IDL.Nat,
    'lastUpdated' : Time,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCommitteeMember' : IDL.Func(
        [IDL.Text, CommitteeRole, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addContact' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'addGalleryItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
        [IDL.Nat],
        [],
      ),
    'addJatre' : IDL.Func(
        [IDL.Text, Time, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'adminAdjustBalance' : IDL.Func([IDL.Nat], [], []),
    'approvePayment' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelReceipt' : IDL.Func([IDL.Nat], [], []),
    'editCommitteeMember' : IDL.Func(
        [IDL.Nat, IDL.Text, CommitteeRole, IDL.Text],
        [],
        [],
      ),
    'editContact' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'editGalleryItem' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'editJatre' : IDL.Func(
        [IDL.Nat, IDL.Text, Time, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'editPaymentConfirmation' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, PaymentMode, IDL.Text, Time],
        [],
        [],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommitteeMembers' : IDL.Func(
        [],
        [IDL.Vec(CommitteeMemberPublic)],
        ['query'],
      ),
    'getCommitteeMembersAdmin' : IDL.Func(
        [],
        [IDL.Vec(CommitteeMember)],
        ['query'],
      ),
    'getContacts' : IDL.Func([], [IDL.Vec(TempleContact)], ['query']),
    'getDonationReport' : IDL.Func([], [DonationReport], ['query']),
    'getDonorList' : IDL.Func([], [IDL.Vec(DonorDetail)], ['query']),
    'getGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
    'getJatres' : IDL.Func([], [IDL.Vec(Jatre)], ['query']),
    'getPendingPayments' : IDL.Func(
        [],
        [IDL.Vec(PaymentConfirmation)],
        ['query'],
      ),
    'getReceipt' : IDL.Func([IDL.Nat], [Receipt], ['query']),
    'getTempleAccountBalance' : IDL.Func([], [TempleAccount], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'regenerateReceipt' : IDL.Func([IDL.Nat], [Receipt], []),
    'rejectPayment' : IDL.Func([IDL.Nat], [], []),
    'removeCommitteeMember' : IDL.Func([IDL.Nat], [], []),
    'removeContact' : IDL.Func([IDL.Nat], [], []),
    'removeGalleryItem' : IDL.Func([IDL.Nat], [], []),
    'removeJatre' : IDL.Func([IDL.Nat], [], []),
    'submitPaymentConfirmation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, PaymentMode, IDL.Text, Time],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };