/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CommitteeMember {
  'id' : bigint,
  'name' : string,
  'role' : CommitteeRole,
  'mobileNumber' : string,
}
export interface CommitteeMemberPublic {
  'id' : bigint,
  'name' : string,
  'role' : CommitteeRole,
}
export type CommitteeRole = { 'member' : null } |
  { 'secretary' : null } |
  { 'president' : null };
export interface DonationReport {
  'totalCollections' : bigint,
  'totalAmount' : bigint,
}
export interface DonorDetail {
  'date' : Time,
  'donorName' : string,
  'paymentMode' : PaymentMode,
  'amount' : bigint,
  'transactionId' : string,
}
export type ExternalBlob = Uint8Array;
export interface GalleryItem {
  'id' : bigint,
  'title' : string,
  'externalBlob' : ExternalBlob,
  'description' : string,
  'mediaType' : string,
}
export interface Jatre {
  'id' : bigint,
  'date' : Time,
  'name' : string,
  'activities' : Array<string>,
  'description' : string,
}
export interface PaymentConfirmation {
  'id' : bigint,
  'status' : PaymentStatus,
  'verificationDate' : [] | [Time],
  'date' : Time,
  'donorName' : string,
  'mobileNumber' : string,
  'amountPaid' : bigint,
  'paymentMode' : PaymentMode,
  'transactionId' : string,
}
export type PaymentMode = { 'upi' : null } |
  { 'cash' : null } |
  { 'gPay' : null } |
  { 'cheque' : null } |
  { 'phonePe' : null };
export type PaymentStatus = { 'pendingVerification' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Receipt {
  'isCancelled' : boolean,
  'date' : Time,
  'donorName' : string,
  'templeName' : string,
  'paymentMode' : PaymentMode,
  'amount' : bigint,
  'receiver' : string,
  'location' : string,
  'receiptNumber' : bigint,
  'transactionId' : string,
}
export interface TempleAccount { 'balance' : bigint, 'lastUpdated' : Time }
export interface TempleContact {
  'id' : bigint,
  'contactType' : string,
  'contactNumber' : string,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCommitteeMember' : ActorMethod<[string, CommitteeRole, string], bigint>,
  'addContact' : ActorMethod<[string, string], bigint>,
  'addGalleryItem' : ActorMethod<
    [string, string, string, ExternalBlob],
    bigint
  >,
  'addJatre' : ActorMethod<[string, Time, string, Array<string>], bigint>,
  'adminAdjustBalance' : ActorMethod<[bigint], undefined>,
  'approvePayment' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelReceipt' : ActorMethod<[bigint], undefined>,
  'editCommitteeMember' : ActorMethod<
    [bigint, string, CommitteeRole, string],
    undefined
  >,
  'editContact' : ActorMethod<[bigint, string, string], undefined>,
  'editGalleryItem' : ActorMethod<[bigint, string, string, string], undefined>,
  'editJatre' : ActorMethod<
    [bigint, string, Time, string, Array<string>],
    undefined
  >,
  'editPaymentConfirmation' : ActorMethod<
    [bigint, string, string, bigint, PaymentMode, string, Time],
    undefined
  >,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommitteeMembers' : ActorMethod<[], Array<CommitteeMemberPublic>>,
  'getCommitteeMembersAdmin' : ActorMethod<[], Array<CommitteeMember>>,
  'getContacts' : ActorMethod<[], Array<TempleContact>>,
  'getDonationReport' : ActorMethod<[], DonationReport>,
  'getDonorList' : ActorMethod<[], Array<DonorDetail>>,
  'getGalleryItems' : ActorMethod<[], Array<GalleryItem>>,
  'getJatres' : ActorMethod<[], Array<Jatre>>,
  'getPendingPayments' : ActorMethod<[], Array<PaymentConfirmation>>,
  'getReceipt' : ActorMethod<[bigint], Receipt>,
  'getTempleAccountBalance' : ActorMethod<[], TempleAccount>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'regenerateReceipt' : ActorMethod<[bigint], Receipt>,
  'rejectPayment' : ActorMethod<[bigint], undefined>,
  'removeCommitteeMember' : ActorMethod<[bigint], undefined>,
  'removeContact' : ActorMethod<[bigint], undefined>,
  'removeGalleryItem' : ActorMethod<[bigint], undefined>,
  'removeJatre' : ActorMethod<[bigint], undefined>,
  'submitPaymentConfirmation' : ActorMethod<
    [string, string, bigint, PaymentMode, string, Time],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];