/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Jatre {
    id: bigint;
    date: Time;
    name: string;
    activities: Array<string>;
    description: string;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface TempleContact {
    id: bigint;
    contactType: string;
    contactNumber: string;
}
export interface DonationReport {
    totalCollections: bigint;
    totalAmount: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface CommitteeMemberPublic {
    id: bigint;
    name: string;
    role: CommitteeRole;
}
export interface CommitteeMember {
    id: bigint;
    name: string;
    role: CommitteeRole;
    mobileNumber: string;
}
export interface PaymentConfirmation {
    id: bigint;
    status: PaymentStatus;
    verificationDate?: Time;
    date: Time;
    donorName: string;
    mobileNumber: string;
    amountPaid: bigint;
    paymentMode: PaymentMode;
    transactionId: string;
}
export interface TempleAccount {
    balance: bigint;
    lastUpdated: Time;
}
export interface Receipt {
    isCancelled: boolean;
    date: Time;
    donorName: string;
    templeName: string;
    paymentMode: PaymentMode;
    amount: bigint;
    receiver: string;
    location: string;
    receiptNumber: bigint;
    transactionId: string;
}
export interface DonorDetail {
    date: Time;
    donorName: string;
    paymentMode: PaymentMode;
    amount: bigint;
    transactionId: string;
}
export interface GalleryItem {
    id: bigint;
    title: string;
    externalBlob: ExternalBlob;
    description: string;
    mediaType: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum CommitteeRole {
    member = "member",
    secretary = "secretary",
    president = "president"
}
export enum PaymentMode {
    upi = "upi",
    cash = "cash",
    gPay = "gPay",
    cheque = "cheque",
    phonePe = "phonePe"
}
export enum PaymentStatus {
    pendingVerification = "pendingVerification",
    approved = "approved",
    rejected = "rejected"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCommitteeMember(name: string, role: CommitteeRole, mobileNumber: string): Promise<bigint>;
    addContact(contactType: string, contactNumber: string): Promise<bigint>;
    addGalleryItem(title: string, description: string, mediaType: string, externalBlob: ExternalBlob): Promise<bigint>;
    addJatre(name: string, date: Time, description: string, activities: Array<string>): Promise<bigint>;
    adminAdjustBalance(newBalance: bigint): Promise<void>;
    approvePayment(paymentId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelReceipt(receiptNumber: bigint): Promise<void>;
    editCommitteeMember(memberId: bigint, name: string, role: CommitteeRole, mobileNumber: string): Promise<void>;
    editContact(contactId: bigint, contactType: string, contactNumber: string): Promise<void>;
    editGalleryItem(itemId: bigint, title: string, description: string, mediaType: string): Promise<void>;
    editJatre(jatreId: bigint, name: string, date: Time, description: string, activities: Array<string>): Promise<void>;
    editPaymentConfirmation(paymentId: bigint, donorName: string, mobileNumber: string, amountPaid: bigint, paymentMode: PaymentMode, transactionId: string, date: Time): Promise<void>;
    getCallerUserRole(): Promise<UserRole>;
    getCommitteeMembers(): Promise<Array<CommitteeMemberPublic>>;
    getCommitteeMembersAdmin(): Promise<Array<CommitteeMember>>;
    getContacts(): Promise<Array<TempleContact>>;
    getDonationReport(): Promise<DonationReport>;
    getDonorList(): Promise<Array<DonorDetail>>;
    getGalleryItems(): Promise<Array<GalleryItem>>;
    getJatres(): Promise<Array<Jatre>>;
    getPendingPayments(): Promise<Array<PaymentConfirmation>>;
    getReceipt(receiptNumber: bigint): Promise<Receipt>;
    getTempleAccountBalance(): Promise<TempleAccount>;
    isCallerAdmin(): Promise<boolean>;
    regenerateReceipt(receiptNumber: bigint): Promise<Receipt>;
    rejectPayment(paymentId: bigint): Promise<void>;
    removeCommitteeMember(memberId: bigint): Promise<void>;
    removeContact(contactId: bigint): Promise<void>;
    removeGalleryItem(itemId: bigint): Promise<void>;
    removeJatre(jatreId: bigint): Promise<void>;
    submitPaymentConfirmation(donorName: string, mobileNumber: string, amountPaid: bigint, paymentMode: PaymentMode, transactionId: string, date: Time): Promise<bigint>;
}
import type { CommitteeMember as _CommitteeMember, CommitteeMemberPublic as _CommitteeMemberPublic, CommitteeRole as _CommitteeRole, DonorDetail as _DonorDetail, ExternalBlob as _ExternalBlob, GalleryItem as _GalleryItem, PaymentConfirmation as _PaymentConfirmation, PaymentMode as _PaymentMode, PaymentStatus as _PaymentStatus, Receipt as _Receipt, Time as _Time, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCommitteeMember(arg0: string, arg1: CommitteeRole, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addCommitteeMember(arg0, to_candid_CommitteeRole_n8(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCommitteeMember(arg0, to_candid_CommitteeRole_n8(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async addContact(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addContact(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addContact(arg0, arg1);
            return result;
        }
    }
    async addGalleryItem(arg0: string, arg1: string, arg2: string, arg3: ExternalBlob): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addGalleryItem(arg0, arg1, arg2, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGalleryItem(arg0, arg1, arg2, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async addJatre(arg0: string, arg1: Time, arg2: string, arg3: Array<string>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addJatre(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addJatre(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async adminAdjustBalance(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminAdjustBalance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminAdjustBalance(arg0);
            return result;
        }
    }
    async approvePayment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approvePayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approvePayment(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelReceipt(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelReceipt(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelReceipt(arg0);
            return result;
        }
    }
    async editCommitteeMember(arg0: bigint, arg1: string, arg2: CommitteeRole, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editCommitteeMember(arg0, arg1, to_candid_CommitteeRole_n8(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editCommitteeMember(arg0, arg1, to_candid_CommitteeRole_n8(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async editContact(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editContact(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editContact(arg0, arg1, arg2);
            return result;
        }
    }
    async editGalleryItem(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editGalleryItem(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editGalleryItem(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async editJatre(arg0: bigint, arg1: string, arg2: Time, arg3: string, arg4: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editJatre(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editJatre(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async editPaymentConfirmation(arg0: bigint, arg1: string, arg2: string, arg3: bigint, arg4: PaymentMode, arg5: string, arg6: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editPaymentConfirmation(arg0, arg1, arg2, arg3, to_candid_PaymentMode_n13(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editPaymentConfirmation(arg0, arg1, arg2, arg3, to_candid_PaymentMode_n13(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCommitteeMembers(): Promise<Array<CommitteeMemberPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommitteeMembers();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommitteeMembers();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCommitteeMembersAdmin(): Promise<Array<CommitteeMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommitteeMembersAdmin();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommitteeMembersAdmin();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContacts(): Promise<Array<TempleContact>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContacts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContacts();
            return result;
        }
    }
    async getDonationReport(): Promise<DonationReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonationReport();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonationReport();
            return result;
        }
    }
    async getDonorList(): Promise<Array<DonorDetail>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonorList();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonorList();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGalleryItems(): Promise<Array<GalleryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGalleryItems();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGalleryItems();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJatres(): Promise<Array<Jatre>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJatres();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJatres();
            return result;
        }
    }
    async getPendingPayments(): Promise<Array<PaymentConfirmation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingPayments();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingPayments();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReceipt(arg0: bigint): Promise<Receipt> {
        if (this.processError) {
            try {
                const result = await this.actor.getReceipt(arg0);
                return from_candid_Receipt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReceipt(arg0);
            return from_candid_Receipt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTempleAccountBalance(): Promise<TempleAccount> {
        if (this.processError) {
            try {
                const result = await this.actor.getTempleAccountBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTempleAccountBalance();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async regenerateReceipt(arg0: bigint): Promise<Receipt> {
        if (this.processError) {
            try {
                const result = await this.actor.regenerateReceipt(arg0);
                return from_candid_Receipt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.regenerateReceipt(arg0);
            return from_candid_Receipt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectPayment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectPayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectPayment(arg0);
            return result;
        }
    }
    async removeCommitteeMember(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeCommitteeMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeCommitteeMember(arg0);
            return result;
        }
    }
    async removeContact(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeContact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeContact(arg0);
            return result;
        }
    }
    async removeGalleryItem(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeGalleryItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeGalleryItem(arg0);
            return result;
        }
    }
    async removeJatre(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeJatre(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeJatre(arg0);
            return result;
        }
    }
    async submitPaymentConfirmation(arg0: string, arg1: string, arg2: bigint, arg3: PaymentMode, arg4: string, arg5: Time): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPaymentConfirmation(arg0, arg1, arg2, to_candid_PaymentMode_n13(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPaymentConfirmation(arg0, arg1, arg2, to_candid_PaymentMode_n13(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return result;
        }
    }
}
function from_candid_CommitteeMemberPublic_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CommitteeMemberPublic): CommitteeMemberPublic {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_CommitteeMember_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CommitteeMember): CommitteeMember {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_CommitteeRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CommitteeRole): CommitteeRole {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_DonorDetail_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DonorDetail): DonorDetail {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_GalleryItem_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GalleryItem): Promise<GalleryItem> {
    return await from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentConfirmation_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentConfirmation): PaymentConfirmation {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMode_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMode): PaymentMode {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_Receipt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Receipt): Receipt {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    role: _CommitteeRole;
}): {
    id: bigint;
    name: string;
    role: CommitteeRole;
} {
    return {
        id: value.id,
        name: value.name,
        role: from_candid_CommitteeRole_n20(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    role: _CommitteeRole;
    mobileNumber: string;
}): {
    id: bigint;
    name: string;
    role: CommitteeRole;
    mobileNumber: string;
} {
    return {
        id: value.id,
        name: value.name,
        role: from_candid_CommitteeRole_n20(_uploadFile, _downloadFile, value.role),
        mobileNumber: value.mobileNumber
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: _Time;
    donorName: string;
    paymentMode: _PaymentMode;
    amount: bigint;
    transactionId: string;
}): {
    date: Time;
    donorName: string;
    paymentMode: PaymentMode;
    amount: bigint;
    transactionId: string;
} {
    return {
        date: value.date,
        donorName: value.donorName,
        paymentMode: from_candid_PaymentMode_n28(_uploadFile, _downloadFile, value.paymentMode),
        amount: value.amount,
        transactionId: value.transactionId
    };
}
async function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    externalBlob: _ExternalBlob;
    description: string;
    mediaType: string;
}): Promise<{
    id: bigint;
    title: string;
    externalBlob: ExternalBlob;
    description: string;
    mediaType: string;
}> {
    return {
        id: value.id,
        title: value.title,
        externalBlob: await from_candid_ExternalBlob_n33(_uploadFile, _downloadFile, value.externalBlob),
        description: value.description,
        mediaType: value.mediaType
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _PaymentStatus;
    verificationDate: [] | [_Time];
    date: _Time;
    donorName: string;
    mobileNumber: string;
    amountPaid: bigint;
    paymentMode: _PaymentMode;
    transactionId: string;
}): {
    id: bigint;
    status: PaymentStatus;
    verificationDate?: Time;
    date: Time;
    donorName: string;
    mobileNumber: string;
    amountPaid: bigint;
    paymentMode: PaymentMode;
    transactionId: string;
} {
    return {
        id: value.id,
        status: from_candid_PaymentStatus_n37(_uploadFile, _downloadFile, value.status),
        verificationDate: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.verificationDate)),
        date: value.date,
        donorName: value.donorName,
        mobileNumber: value.mobileNumber,
        amountPaid: value.amountPaid,
        paymentMode: from_candid_PaymentMode_n28(_uploadFile, _downloadFile, value.paymentMode),
        transactionId: value.transactionId
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isCancelled: boolean;
    date: _Time;
    donorName: string;
    templeName: string;
    paymentMode: _PaymentMode;
    amount: bigint;
    receiver: string;
    location: string;
    receiptNumber: bigint;
    transactionId: string;
}): {
    isCancelled: boolean;
    date: Time;
    donorName: string;
    templeName: string;
    paymentMode: PaymentMode;
    amount: bigint;
    receiver: string;
    location: string;
    receiptNumber: bigint;
    transactionId: string;
} {
    return {
        isCancelled: value.isCancelled,
        date: value.date,
        donorName: value.donorName,
        templeName: value.templeName,
        paymentMode: from_candid_PaymentMode_n28(_uploadFile, _downloadFile, value.paymentMode),
        amount: value.amount,
        receiver: value.receiver,
        location: value.location,
        receiptNumber: value.receiptNumber,
        transactionId: value.transactionId
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    member: null;
} | {
    secretary: null;
} | {
    president: null;
}): CommitteeRole {
    return "member" in value ? CommitteeRole.member : "secretary" in value ? CommitteeRole.secretary : "president" in value ? CommitteeRole.president : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upi: null;
} | {
    cash: null;
} | {
    gPay: null;
} | {
    cheque: null;
} | {
    phonePe: null;
}): PaymentMode {
    return "upi" in value ? PaymentMode.upi : "cash" in value ? PaymentMode.cash : "gPay" in value ? PaymentMode.gPay : "cheque" in value ? PaymentMode.cheque : "phonePe" in value ? PaymentMode.phonePe : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pendingVerification: null;
} | {
    approved: null;
} | {
    rejected: null;
}): PaymentStatus {
    return "pendingVerification" in value ? PaymentStatus.pendingVerification : "approved" in value ? PaymentStatus.approved : "rejected" in value ? PaymentStatus.rejected : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CommitteeMemberPublic>): Array<CommitteeMemberPublic> {
    return value.map((x)=>from_candid_CommitteeMemberPublic_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CommitteeMember>): Array<CommitteeMember> {
    return value.map((x)=>from_candid_CommitteeMember_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DonorDetail>): Array<DonorDetail> {
    return value.map((x)=>from_candid_DonorDetail_n26(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GalleryItem>): Promise<Array<GalleryItem>> {
    return await Promise.all(value.map(async (x)=>await from_candid_GalleryItem_n31(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PaymentConfirmation>): Array<PaymentConfirmation> {
    return value.map((x)=>from_candid_PaymentConfirmation_n35(_uploadFile, _downloadFile, x));
}
function to_candid_CommitteeRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CommitteeRole): _CommitteeRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_PaymentMode_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMode): _PaymentMode {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMode): {
    upi: null;
} | {
    cash: null;
} | {
    gPay: null;
} | {
    cheque: null;
} | {
    phonePe: null;
} {
    return value == PaymentMode.upi ? {
        upi: null
    } : value == PaymentMode.cash ? {
        cash: null
    } : value == PaymentMode.gPay ? {
        gPay: null
    } : value == PaymentMode.cheque ? {
        cheque: null
    } : value == PaymentMode.phonePe ? {
        phonePe: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CommitteeRole): {
    member: null;
} | {
    secretary: null;
} | {
    president: null;
} {
    return value == CommitteeRole.member ? {
        member: null
    } : value == CommitteeRole.secretary ? {
        secretary: null
    } : value == CommitteeRole.president ? {
        president: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
